export default {
	ActionTypes: {

		/* UI */
		CHANGE_FILTERS_SELECTION: "CHANGE_FILTERS_SELECTION",
		CHANGE_BUCKET_SELECTION:  "CHANGE_BUCKET_SELECTION",
		CHANGE_TWEETS_SELECTION:  "CHANGE_TWEETS_SELECTION",

		/* GETTING DATA */

		/** GET FILTERS **/
		GET_FILTERS: "GET_FILTERS",
		RECEIVE_FILTERS_SENDING:   "RECEIVE_FILTERS_SENDING",
		RECEIVE_FILTERS_SUCCEEDED: "RECEIVE_FILTERS_SUCCEEDED",
		RECEIVE_FILTERS_FAILED:    "RECEIVE_FILTERS_FAILED",

		/** GET EVENT BUCKETS METADATA **/
		GET_EVENTBUCKETS_METADATA: "GET_EVENTBUCKETS_METADATA",
		RECEIVE_EVENTBUCKETS_SENDING:   "RECEIVE_EVENTBUCKETS_SENDING",
		RECEIVE_EVENTBUCKETS_SUCCEEDED: "RECEIVE_EVENTBUCKETS_SUCCEEDED",
		RECEIVE_EVENTBUCKETS_FAILED:    "RECEIVE_EVENTBUCKETS_FAILED",

		/** GET BUCKET DATA **/
		GET_BUCKET_DATA: "GET_BUCKET_DATA",
		RECEIVE_BUCKET_SENDING:   "RECEIVE_BUCKET_SENDING",
		RECEIVE_BUCKET_SUCCEEDED: "RECEIVE_BUCKET_SUCCEEDED",
		RECEIVE_BUCKET_FAILED:    "RECEIVE_BUCKET_FAILED",

		/* SENDING ACTIONS */

		/** SEND TWEET **/

		SEND_TWEET: "SEND_TWEET",
		SEND_TWEET_SENDING:   "SEND_TWEET_SENDING",
		SEND_TWEET_SUCCEEDED: "SEND_TWEET_SUCCEEDED",
		SEND_TWEET_FAILED:    "SEND_TWEET_FAILED",

		/** SEND DIRECT MESSAGE **/
		SEND_DIRECT_MESSAGE: "SEND_DIRECT_MESSAGE",
		SEND_DIRECT_MESSAGE_SENDING:   "SEND_DIRECT_MESSAGE_SENDING",
		SEND_DIRECT_MESSAGE_SUCCEEDED: "SEND_DIRECT_MESSAGE_SUCCEEDED",
		SEND_DIRECT_MESSAGE_FAILED:    "SEND_DIRECT_MESSAGE_FAILED",

		/** SEND FAVORITE **/
		SEND_FAVORITE: "SEND_FAVORITE",
		SEND_FAVORITE_SENDING:   "SEND_FAVORITE_SENDING",
		SEND_FAVORITE_SUCCEEDED: "SEND_FAVORITE_SUCCEEDED",
		SEND_FAVORITE_FAILED:    "SEND_FAVORITE_FAILED",

		/** SEND RETWEET **/
		SEND_RETWEET: "SEND_RETWEET",
		SEND_RETWEET_SENDING:   "SEND_RETWEET_SENDING",
		SEND_RETWEET_SUCCEEDED: "SEND_RETWEET_SUCCEEDED",
		SEND_RETWEET_FAILED:    "SEND_RETWEET_FAILED",

		/** SEND FOLLOW **/
		SEND_FOLLOW: "SEND_FOLLOW",
		SEND_FOLLOW_SENDING:   "SEND_FOLLOW_SENDING",
		SEND_FOLLOW_SUCCEEDED: "SEND_FOLLOW_SUCCEEDED",
		SEND_FOLLOW_FAILED:    "SEND_FOLLOW_FAILED",
	}
}